### ISSUE TITLE
Enhancement: Rider Blacklist Config

### ISSUE THREAD

**Issue by gaforb** [Mico27/RoR2-RideMeExtended-Mod#1]
A way of blacklisting certain vanilla / modded characterbodies from being rideable. Ideally I'd like to make it so only player characters are rideable.

**Comment by Mico27** [comment]
Yeah I could expose the list of characterbodies to blacklist in the config. I'll work on that for the next update.

**Comment by Mico27** [comment]
1.0.2 now can blacklist in the config (make sure you run the game once with the mod to update the config)
